### ISSUE TITLE
Compilation error in kmain.c

### ISSUE THREAD

**Issue by mmkumr** [cstack/osdev#1]
While compiling the kmain.c it is showing an error 'cast to pointer from integer of different size [-Wint-to-pointer-cast]' on this line 'multiboot_info_t *mbinfo = (multiboot_info_t *) ebx;'. Checkout the attached file 
![screenshot from 2018-12-31 18-01-48](https://user-images.githubusercontent.com/17456593/50560373-3cb62880-0d26-11e9-8460-fe49bb69295f.png)
below.

**Comment by cstack** [comment]
@mmkumr Hi! I haven't touched this project in a while so my development environment isn't set up to quickly debug or fix this. If you have a fix I'd gladly review it!

**Comment by mmkumr** [comment]
Thanks for your response.:) I have added `-Wall -Wextra -Werror -c 3 -Wno-unused-variable -Wno-return-type` this line to my Makefile.
